name: Build and publish at push

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v2
      - name: Build image 
        run: docker build -t ${{ github.event.repository.name }} .
      - name: Install doctl 
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_API_TOKEN}}
      - name: Log in to DO Container Registry 
        run: doctl registry login --expiry-seconds 600
      - name: Tag image 
        run:
          docker tag ${{ github.event.repository.name }} \
          ${{ secrets.DO_REGISTRY }}/${{ github.event.repository.name}}:latest
      - name: Push image to DO Container Registry 
        run: docker push ${{ secrets.DO_REGISTRY }}/${{ github.event.repository.name }}:latest
